Feature/final fix of bugs
Andry-art/Andry-art-checkmoney-iTechArt- pull request #17
Opened 2022-02-08 13:06 UTC by Andry-art

2022-02-09 10:01 UTC, sergej-prilutskiy requested changes

2022-02-09 10:01 UTC, sergej-prilutskiy commented on packages/App/src/balance/debits/ListOfDebits.tsx
> +        style={keyDeb === lastKey ? styles.lastItem : styles.listItem}
Maybe you can use `ItemSeparatorComponent` here?

2022-02-09 10:01 UTC, sergej-prilutskiy commented on packages/App/src/balance/statistic/MoneyFlow.tsx
> +            {left ? Math.round(left * 100) / 100 : 0}
Looks like rounding should include devision also

2022-02-11 13:33 UTC, Andry-art commented on packages/App/src/balance/debits/ListOfDebits.tsx
> +        style={keyDeb === lastKey ? styles.lastItem : styles.listItem}
Nope) I rendered list by using map inside of ScrollView, so there is no kind of option)

2022-02-14 08:57 UTC, merged