Feature/wallet
Andry-art/Andry-art-checkmoney-iTechArt- pull request #7
Opened 2021-12-31 11:30 UTC by Andry-art

I think I have made all the functions that are required. But maybe you will have questions about some realization. I want to warn you in advance)) For example I haven't used formik in two screens, cuz they were so simple and I assume it`s not important to implement it there. So I used simple input and kept changes in state. And I`ve made component for modal, but in component where needs add transaction and correct it, I`ve made modal inside component, cuz it has some distinguish, so in my opinion it was easier than modified Modal component. 
And I`m so sorry how much you need to review. But be optimistic and consider this my gift for you for the new year.

2021-12-31 14:13 UTC, sergej-prilutskiy requested changes
Some issued should be resolved in many places, so I'll mention them here:
- Navigation screens `navigation` prop is typed as `any`. This isn't a good choice. Take a look on Typescript guide from [docs](https://reactnavigation.org/docs/typescript). 
- Callbacks passed as props are not wrapped in `useCallback()`. Same for object literals in props
- Naming of async actions. The convention is to name async actions as `doThingRequest`,  `doThingSuccess`, `doThingFailure`. This makes debugging easier and code more readable

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/Balance.tsx
> +          {receivedWalletItems.reduce((sum, cur) => {
It will be more convenient to have all this logic inside selectors, not in the component. Now the component knows too much on how the data is stored. The component only needs the amount, not the array of wallet records. This will also improve the performance. Take a look into `toolkit` [docs](https://redux-toolkit.js.org/api/createSelector) page on using `reselect`

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +const AddMonetaryMovements: FC = ({navigation}: any) => {
Let's use this [guide](https://reactnavigation.org/docs/typescript) to annotate screens' `navigation` prop.

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/selectors/walletItems.tsx
> +export const WalletItems = (state: RootState) => {
```suggestion
export const walletItems = (state: RootState) => {
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/selectors/walletItems.tsx
> +export const IsLoadingWallet = (state: RootState) => {
```suggestion
export const isLoadingWallet = (state: RootState) => {
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +    transactionType: boolean,
It's a best practice to name Boolean variables starting with `is`. In this case it might be `isIncomeTransaction`

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +      chosenWallet.transactions.length === 0
If `chosenWallet` is `undefined`, this line will produce an error

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +    const [chosenWallet] = receivedWalletItems.filter(it => it.id === key);
```suggestion
    const chosenWallet = receivedWalletItems.find(it => it.id === key);
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +          keyExtractor={it => it}
Maybe `it => it.id`?

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CategoriesInAddMoneyMove.tsx
> +  chosen: {icon: string; category: string};
This type `{icon: string; category: string}` is reused across the app. Maybe it should be extracted to a separate type?

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CategoriesInAddMoneyMove.tsx
> +  pic: string;
```suggestion
  picture: string;
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CorrectTransaction.tsx
> +const income = ['iconUnknownSource', 'iconSalarySource'];
If these values are also reused, let's also create a type for them. It might be a `iconUnknownSource | iconSalarySource ...`

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CorrectTransaction.tsx
> +    if (difference < 0) {
Maybe it can be replaced with `Math.abs()` on line 58

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/NewCard.tsx
> +    onSubmit: (values: {cardName: string; amount: string}) => {
You can pass `values` type as a generic parameter in `useFormik<{cardName: string ... }>()`

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/Wallet.tsx
> +  const [refItem, setRefItem] = useState<FlatList<WalletInfo> | null>();
Why are you using `useState` here to use it as a ref?

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/Wallet.tsx
> +          {receivedWalletItems.reduce((sum, cur) => {
This also can be moved to selectors

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/Store.tsx
> +const SagaMiddlewareWallet = createSagaMiddleware();
You should only create one saga middleware on the app (and run it afterwards). 
```javascript
export function* rootSaga(): Generator {
  yield all([
    SagaMiddleware(),
    SagaMiddlewareWallet(),
  ]);
}
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/reducers/Wallet.tsx
> +    .addCase('GET_WALLET_ITEMS', state => ({...state, isLoading: true}))
```suggestion
    .addCase(getWalletItems, state => ({...state, isLoading: true}))
```

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/saga/walletActionsSaga.tsx
> +export const getWalletItemsSuccess = createAction<Array<WalletInfo>>(
All actions for one feature should be created in a file near the reducer. You should not create actions in `saga` directory

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/saga/walletItemsRequest.tsx
> +  if (action.type === 'FILTER_EXPENSES') {
If the request is coming to the same URL, maybe `if`-statement could be placed right where you're dispatching different actions with results?

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/saga/walletItemsRequest.tsx
> +addNewCard;
?)

2021-12-31 14:13 UTC, sergej-prilutskiy commented on packages/App/src/store/reducers/Wallet.tsx
> +      state.walletContent = state.walletContent.map(it =>
Just a question. Ho do you think, why does not redux throw an error when you're mutating state here?

2022-01-03 18:28 UTC, Andry-art commented on packages/App/src/balance/wallet/AddMonetaryMovements.tsx
> +          keyExtractor={it => it}
And forgot to text about this) There is two arrays, and inside it is strings. And every string is unique, so I just used it as a key as well

2022-01-03 18:39 UTC, sergej-prilutskiy reviewed
Looks better. Some minor updates proposed)

2022-01-03 18:39 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CategoriesInAddMoneyMove.tsx
> +    chosenCategory(picture, title);
Why not just call `onPress` here?

2022-01-03 18:39 UTC, sergej-prilutskiy commented on packages/App/src/balance/wallet/CorrectTransaction.tsx
> +          renderItem={it => (
`useCallback`?

2022-01-03 18:39 UTC, sergej-prilutskiy commented on packages/App/src/store/reducers/actions/walletActionsSaga.tsx
> +
No need to create separate file for actions dispatched from sagas. The request action does not make sense without success and failure actions, so let's move those to `packages/App/src/store/actions/walletActions.tsx`

2022-01-04 09:36 UTC, merged